### ISSUE TITLE
Define default column presentation in en.yml?

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#77]
In at least one or two projects, we've gotten away from doing things like:

```rb
f.label :my_column, 'My Column'
```

and instead have added the following to the `en.yml`:

```yml
en:
  activerecord:
    attributes:
      my_model:
        my_column: 'My Column'
```

and done away with the second argument to `label`. This has a few advantages from my point of view:

* It'll always be presented consistently to the users in both labels and ActiveRecord error messages unless you choose to overwrite it manually in a particular instance.
* Developers no longer have to remember the exact way a column was presented elsewhere (e.g. was it "My column" or "My Column" or just "Column").

Unfortunately, it doesn't get picked up by Ransack (so `f.label :my_column_eq` would still need the second argument).
